#!/usr/bin/env python
# SPDX-License-Identifer: GPL-3.0-or-later

import logging
import os
import sys

from gnome_browser_connector import Application

SERVICE_ARG = '--gapplication-service'

if __name__ == '__main__':
    logging.basicConfig(
        format="%(asctime)s: [%(process)d] %(levelname)s %(name)s %(message)s",
        level=getattr(
            logging,
            os.getenv("GNOME_BROWSER_EXTENSION_LOGLEVEL", "warning").upper()
        ),
        stream=sys.stderr
    )
    logging.debug('Main')
    if hasattr(sys, 'ps1'):
        logging.info('Use CTRL+D to quit')

    IS_SERVICE = SERVICE_ARG in sys.argv
    if IS_SERVICE:
        sys.argv.remove(SERVICE_ARG)

    app = Application(IS_SERVICE)
    app.run(sys.argv)

    logging.debug('Quit')
